# Generated by Django 4.2.6 on 2023-10-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("height", models.DecimalField(decimal_places=2, max_digits=3)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=3)),
                ("bmi", models.IntegerField()),
                ("bodyFat", models.DecimalField(decimal_places=2, max_digits=2)),
                ("muscle", models.DecimalField(decimal_places=2, max_digits=2)),
                ("visceral", models.IntegerField()),
                ("calories", models.IntegerField()),
                ("metabolicAge", models.IntegerField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
