# Generated by Django 4.2.6 on 2023-10-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_createdat_profile_updatedat"),
        ("records", "0003_alter_record_bodyfat_alter_record_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profileRecords",
                to="profiles.profile",
            ),
        ),
    ]
