# Generated by Django 4.2.6 on 2023-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0004_alter_record_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="bodyFat",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="record",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="record",
            name="muscle",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="record",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
