# Generated by Django 4.2.6 on 2023-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0005_alter_record_bodyfat_alter_record_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="bmi",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
