version: '3.8'
services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - static_volume:/app/staticfiles
      - data_volume:/app/data
    ports:
      - 8002:8002
    restart: always
    env_file: ./app/.env.production

volumes:
  static_volume:
  data_volume:
  postgres_data:
