version: '3.8'
services:
  web:
    build:
      context: .
      args:
        INSTALL_PROD_DEPENDENCIES: "true"
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - static_volume:/app/staticfiles
      - data_volume:/app/data
    ports:
      - 8002:8002
    restart: always
    env_file: ./app/prod.env
  
volumes:
  static_volume:
  data_volume:
  postgres_data: